spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userConstruction?createDatabaseIfNotExist=True
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

